language: csharp
mono:
  - latest

solution: Aragas.Core.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore Aragas.Core.sln

script:
  - xbuild /p:Configuration=Release Aragas.Core.sln
  - xbuild /p:Configuration=Debug Aragas.Core.sln

notifications:
  email:
    on_success: always
